#!/usr/bin/env python3

import rospy
from sensor_msgs.msg import JointState
from markers import *
from proyfunctions import *

if __name__ == '__main__':
    rospy.init_node("testInvKine")
    pub = rospy.Publisher('joint_states', JointState, queue_size=1)
    bmarker      = BallMarker(color['RED'])
    bmarker_des  = BallMarker(color['GREEN'])
    jnames = ['joint_1', 'joint_2','joint_3','joint_4','joint_5','joint_6']
    xd = np.array([-1, 1.6, 0.9])
    q0 = np.array([0, 0, 0, 0, 0, 0, 0, 0])
    q = ikine(xd, q0)
    T = fkine_fanuc(q)
    print('Posicion cartesiana:\n', np.round(T,4))
    print(q)	
    bmarker.position(T)
    bmarker_des.xyz(xd)
    jstate = JointState()
    jstate.header.stamp = rospy.Time.now()
    jstate.name = jnames
    jstate.position = q
    rate = rospy.Rate(100)
    while not rospy.is_shutdown():
        jstate.header.stamp = rospy.Time.now()
        pub.publish(jstate)
        bmarker.publish()
        bmarker_des.publish()
        rate.sleep()
