#!/usr/bin/env python3
import rospy
from sensor_msgs.msg import JointState
import numpy as np

if __name__ == '__main__':
    rospy.init_node("test_gripper_only")
    pub = rospy.Publisher('joint_states', JointState, queue_size=1)
    jnames = ['joint_1', 'joint_2','joint_3','joint_4','joint_5','joint_6', 
              'gripper_base-finger_1', 'gripper_base-finger_2']
    q = np.zeros(6)
    finger_open = np.array([0.04, 0.04])
    finger_close = np.array([0.0, 0.0])
    rate = rospy.Rate(1)
    while not rospy.is_shutdown():
        # Alterna abierto/cerrado cada 2 segundos
        finger = finger_open if (rospy.get_time() % 4) < 2 else finger_close
        q_total = np.concatenate((q, finger))
        jstate = JointState()
        jstate.header.stamp = rospy.Time.now()
        jstate.name = jnames
        jstate.position = q_total
        pub.publish(jstate)
        rate.sleep()
