joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Controladores de esfuerzo individuales
joint_1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint_1

joint_2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint_2

joint_3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint_3

joint_4_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint_4

joint_5_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint_5

joint_6_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint_6

gripper_base_finger_1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: gripper_base_finger_1

gripper_base_finger_2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: gripper_base_finger_2





