joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - gripper_base_finger_1
    - gripper_base_finger_2
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint_1: {trajectory: 0.1, goal: 0.1}
    joint_2: {trajectory: 0.1, goal: 0.1}
    joint_3: {trajectory: 0.1, goal: 0.1}
    joint_4: {trajectory: 0.1, goal: 0.1}
    joint_5: {trajectory: 0.1, goal: 0.1}
    joint_6: {trajectory: 0.1, goal: 0.1}
    gripper_base_finger_1: {trajectory: 0.01, goal: 0.01}
    gripper_base_finger_2: {trajectory: 0.01, goal: 0.01}
  gains:
    joint_1: {p: 100, i: 0.01, d: 1.0}
    joint_2: {p: 100, i: 0.01, d: 1.0}
    joint_3: {p: 100, i: 0.01, d: 1.0}
    joint_4: {p: 100, i: 0.01, d: 1.0}
    joint_5: {p: 100, i: 0.01, d: 1.0}
    joint_6: {p: 100, i: 0.01, d: 1.0}
    gripper_base_finger_1: {p: 10.0, i: 0.01, d: 0.1}
    gripper_base_finger_2: {p: 10.0, i: 0.01, d: 0.1}

  state_publish_rate: 50
  action_monitor_rate: 10

gazebo_ros_control:
  pid_gains:
    joint_1: {p: 100, i: 0.01, d: 1.0}
    joint_2: {p: 100, i: 0.01, d: 1.0}
    joint_3: {p: 100, i: 0.01, d: 1.0}
    joint_4: {p: 100, i: 0.01, d: 1.0}
    joint_5: {p: 100, i: 0.01, d: 1.0}
    joint_6: {p: 100, i: 0.01, d: 1.0}
    gripper_base_finger_1: {p: 10.0, i: 0.01, d: 0.1}
    gripper_base_finger_2: {p: 10.0, i: 0.01, d: 0.1}






